[build]
  command = "bundle install --jobs=4 --retry=3 --path vendor/bundle && npm install && npx tailwindcss -i ./src/input.css -o ./assets/css/tailwind.css && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.4"
  BUNDLER_VERSION = "2.7.1"
  NODE_VERSION = "20.18.0"
  NODE_ENV = "development"

[context.deploy-preview]
  command = "bundle install --jobs=4 --retry=3 --path vendor/bundle && npm ci --no-audit --prefer-offline && npx browserslist@latest --update-db || true && npm run build && bundle exec jekyll build --destination _site"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
